main:
  - name: "Home"
    url: "/"
    weight: 1

  - name: "About Us"
    url: "/about-us/"
    weight: 2

  - name: "Our Team"
    url: "/our-team/"
    weight: 3

  - name: "Blog"
    url: "/blog/"
    weight: 4

buttons:
  - name: "Contact Us"
    url: "/contact-us/"
    weight: 5

footer:
  - name: "Home"
    url: "/"
    weight: 1

  - name: "About Us"
    url: "/about-us/"
    weight: 2

  - name: "Our Team"
    url: "/our-team/"
    weight: 3

  - name: "Blog"
    url: "/blog/"
    weight: 4
