title: "FSA"
description: "Better Health Everyday"
images: 
  - "images/hero-image.png"

logo: "arrow-up.png"

favicons:
  themeColor: "#FFFFFF"
  backgroundColor: "#FFFFFF"
  faviconColor: "#000000"

social:
  dribbble: "#"
  instagram: "#"
  facebook: "#"
  twitter: "#"

location:
  - "🇦🇪 Shams Business Center, Al Messaned, Sharjah, UAE"
  - "🇮🇳 Patel Tower, N-6 road, Aurangabad, Maharashtra, India"

contact:
  - "info@fsahealthcare.com"
  - "207.555.0119"

copyright: "© 2025 FSA All Rights Reserved"

